modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
[[mods]]
modId="combatimprovement"
version="${file.jarVersion}"
displayName="Combat Improvement"
logoFile="combatimprovement.png"
credits=""
authors="ArkadiyHimself"
description='''

'''
[[dependencies.combatimprovement]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.combatimprovement]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
